# btop — GÉNÉRÉ par material-you-gnome, ne pas éditer.
# Source: {{image}}  ·  Mode: {{mode}}

theme[main_bg]="{{colors.surface.default.hex}}"
theme[main_fg]="{{colors.on_surface.default.hex}}"
theme[title]="{{colors.on_surface.default.hex}}"
theme[hi_fg]="{{colors.primary.default.hex}}"
theme[selected_bg]="{{colors.secondary_container.default.hex}}"
theme[selected_fg]="{{colors.on_secondary_container.default.hex}}"
theme[inactive_fg]="{{colors.outline.default.hex}}"
theme[graph_text]="{{colors.on_surface_variant.default.hex}}"
theme[meter_bg]="{{colors.surface_container_highest.default.hex}}"
theme[proc_misc]="{{colors.tertiary.default.hex}}"

theme[cpu_box]="{{colors.outline_variant.default.hex}}"
theme[mem_box]="{{colors.outline_variant.default.hex}}"
theme[net_box]="{{colors.outline_variant.default.hex}}"
theme[proc_box]="{{colors.outline_variant.default.hex}}"
theme[div_line]="{{colors.outline_variant.default.hex}}"

theme[temp_start]="{{base16.base0b.default.hex}}"
theme[temp_mid]="{{base16.base0a.default.hex}}"
theme[temp_end]="{{base16.base08.default.hex}}"

theme[cpu_start]="{{colors.primary.default.hex}}"
theme[cpu_mid]="{{colors.tertiary.default.hex}}"
theme[cpu_end]="{{colors.secondary.default.hex}}"

theme[free_start]="{{base16.base0d.default.hex}}"
theme[free_mid]=""
theme[free_end]="{{base16.base0c.default.hex}}"

theme[cached_start]="{{colors.tertiary.default.hex}}"
theme[cached_mid]=""
theme[cached_end]="{{colors.primary.default.hex}}"

theme[available_start]="{{base16.base0a.default.hex}}"
theme[available_mid]=""
theme[available_end]="{{base16.base09.default.hex}}"

theme[used_start]="{{base16.base08.default.hex}}"
theme[used_mid]=""
theme[used_end]="{{base16.base0e.default.hex}}"

theme[download_start]="{{colors.primary.default.hex}}"
theme[download_mid]=""
theme[download_end]="{{colors.tertiary.default.hex}}"

theme[upload_start]="{{colors.secondary.default.hex}}"
theme[upload_mid]=""
theme[upload_end]="{{colors.error.default.hex}}"

theme[process_start]="{{colors.primary.default.hex}}"
theme[process_mid]="{{colors.tertiary.default.hex}}"
theme[process_end]="{{colors.secondary.default.hex}}"
